// precompiled header file
#include <wx/wx.h>
#include <wx/config.h>
#include <wx/listctrl.h>
#include <wx/splitter.h>
#include <wx/notebook.h>
#include <wx/aui/aui.h>
#include <wx/progdlg.h>
#include <wx/wfstream.h>
#include <wx/zipstrm.h>
#include <wx/txtstrm.h>
#include <wx/aboutdlg.h>
#include <wx/cmdline.h>
#include <wx/statline.h>
#include <wx/hyperlink.h>
#include <wx/evtloop.h>
#include <wx/tipwin.h>
#include <wx/mstream.h>
#include <wx/aui/auibar.h>
#include <wx/aui/auibook.h>
#include <windows.h>
#include <map>
#include <set>
#include <fstream>
#include <algorithm>
#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <assert.h>
